"""create tables book and page

Revision ID: 3bb24cc527a8
Revises: 539ba9f2f2e1
Create Date: 2014-03-10 17:59:10.719215

"""

# revision identifiers, used by Alembic.
revision = '3bb24cc527a8'
down_revision = '539ba9f2f2e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.create_table("book",
        sa.Column("id", sa.String(100), primary_key=True),
        sa.Column("title", sa.String(255), unique=True),
        sa.Column("publisher", sa.String(255)),
        sa.Column("contributor", sa.String(255)),
        sa.Column("volume", sa.String(50)),
        sa.Column("img_url", sa.String(255)),
        sa.Column("contributor", sa.String(255))
    )
    
    op.create_table("page",
        sa.Column("id", sa.Integer, autoincrement=True),
        sa.Column("book_id", sa.String(100), sa.ForeignKey("book.id"), unique=True),
        sa.Column("archiveURL", sa.String(255), nullable=False, unique=True),
        sa.Column("page", sa.String(10)),
        
        sa.PrimaryKeyConstraint("id", "book_id")
    )

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
