"""empty message

Revision ID: 539ba9f2f2e1
Revises: None
Create Date: 2014-03-10 17:36:30.228935

"""

# revision identifiers, used by Alembic.
revision = '539ba9f2f2e1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
